#!/bin/bash

# lint check
run_linter() {
  poetry run flake8 .
}

# lint check
run_formatter() {
  poetry run black .
}

# format notebooks
clean_notebook(){
  local NOTEBOOK_FILE=$1
  poetry run jupyter nbconvert --clear-output --inplace $NOTEBOOK_FILE
}


# Shows usage
usage() {
  printf "  lint\t\t\t\t\tRuns a flake8 lint check against PEP 8\n"
  printf "  format\t\t\t\tModifies non PEP 8 compliant code to be style compliant\n"
  printf "  clean-notebook <notebook-path> \tRemoves rendered html from jupyter notebooks\n"
}


case $1 in
  lint)
    run_linter
    ;;
  format)
    run_formatter
    ;;
  clean-notebook)
    clean_notebook $2
    ;;
  *)
    usage
    ;;
esac
